# Site settings
title: Dictionnaire en ligne
email: yves.doumergue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dictionnaire en ligne.
url: "http://ledico.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /:categories.html